imports:
    - { resource: "@CoffreoAuthenticationBundle/Resources/config/config.yml" }

services:
    app.coffreo_user_provider:
        class: App\Security\UserProvider
        tags:
        - { name: "coffreo_authentication.user_provider"}
